ga_config:
  pop_size: 200
  generations: 2000
  crossover_rate: 0.85
  mutation_rate: 0.15
  elitism_count: 2

problem_name: "mtsp"

problem_config:
  num_workers: 3
  depot: [30, 30]
  cities:
    - [5, 10]
    - [15, 25]
    - [30, 5]
    - [40, 20]
    - [20, 40]
    - [35, 35]
    - [10, 30]
    - [50, 45]
    - [45, 10]
    - [60, 30]
    - [25, 15]
    - [55, 20]
    - [70, 10]
    - [80, 25]
    - [65, 40]
    - [90, 30]
    - [75, 50]
    - [85, 15]
    - [95, 35]
    - [40, 50]
    - [10, 5]
    - [20, 25]
    - [35, 10]
    - [50, 15]
    - [60, 5]
    - [70, 20]
    - [30, 50]
    - [45, 25]
    - [55, 35]
    - [65, 15]
